apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nameOverride }}
spec:
  selector:
    app: {{ .Values.nameOverride }}
  ports:
  - name: {{ .Values.nameOverride }}
    nodePort: {{ .Values.service.nodePortNumber }}
    port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.port }}
  sessionAffinity: None
  type: {{ .Values.service.type }}
status:
  loadBalancer: {}