apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    field.cattle.io/creatorId: {{ .Values.propietario }}
    pv.kubernetes.io/bind-completed: "yes"
  creationTimestamp: null
  finalizers:
  - kubernetes.io/pvc-protection
  name: "v-{{ .Values.nameOverride }}"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.volumenes.espaciopvc }}
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: "pv-{{ .Values.nameOverride }}"
status: {}